[netease]
# 网易云音乐API地址，使用 https://github.com/neteasecloudmusicapienhanced/api-enhanced
neteaseAPI = http://127.0.0.1:3000
# 网易云音乐Cookie，留空则使用未登录状态
cookies = ""

[qq]
# QQ音乐API地址，使用 https://github.com/RayQuantum/QQMusicApi_QR
qqAPI = http://127.0.0.1:3300
# QQ音乐Cookie，留空则使用未登录状态
cookies = ""
# QQ音乐FM频道ID，具体可查看API文档或使用默认值99
qqfm = "99"

